apiVersion: v1
data:
  DB_DATABASE: expenditures
  DB_HOST: mysql
  DB_PASSWORD: toor
  DB_PORT: "3306"
  DB_USER: root
  ORIGIN_PORT: "60869"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: backend-backend--env
  name: backend--env
